language: node_js
sudo: false
env:
  - CXX=g++-4.9
node_js:
  - '12.13.1'
  - '10'
  - '8'
script:
  - yarn test
  - yarn run enforce
  - yarn run lint
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libpoppler-cpp-dev
    - libpoppler-private-dev
    - g++-4.9
